import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: "./font/coc.otf",
  display: "swap",
});

export const metadata = {
  metadataBase: new URL("http://www.localhoast:3000/"),
  title: {
    default: "Gems",
    template: "%s",
  },
  verification: {
    google: "google-site-verification=40042342432", // update
  },
};

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   verification: {
//     google: "google-site-verification=xxxxxx",
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className="bg-bg">{children}</div>
      </body>
    </html>
  );
}
