GET  http://localhost:3000/api/lang
Content-Type: application/json

{
  "lang": "fr",
  "title": "Bijoux Clash of Clans",
  "description": "Vous pouvez maintenant gagner une quantité illimitée des bijoux Clash of Clans pour acheter des ressources et remplir les réserves d'élixir et d'or au maximum. Il vous suffit de vous inscrire maintenant et d'obtenir un code pour des bijoux Clash of Clans. Achetez tous les skins que vous aimez dans la boutique, remplissez les réservoirs de votre village principal, développez votre village et votre armée pour devenir le plus fort de votre tribu et le plus puissant dans la Guerre des Clans.",
  "buttons": {
    "next": "Suivant",
    "back": "Précédent",
    "submit": "Confirmer"
  },
  "labels": {
    "name": "Nom",
    "username": "ID",
    "device": "Appareil",
    "email": "E-mail",
    "wait": "Veuillez patienter",
    "emailNotice": "Remarque : les bijoux seront envoyés par e-mail"
  },
  "h1": {
    "one": "Bijoux Gratuits",
    "two": "Second Vide"
  },
  "radio": {
    "device": {
      "android": "Android",
      "ios": "Apple",
      "other": "Autre"
    },
    "card": {
      "first": {
        "title": "Pack de Bijoux",
        "amount": "1200",
        "image": "path",
        "alt": "Pack de Bijoux"
      },
      "second": {
        "title": "Coffre de Bijoux",
        "amount": "2500",
        "image": "path",
        "alt": "Coffre de Bijoux"
      },
      "third": {
        "title": "Trésor de Bijoux",
        "amount": "6500",
        "image": "path",
        "alt": "Trésor de Bijoux"
      }
    }
  },
  "section": {
    "howTo": {
      "title": "Comment obtenir des bijoux Clash gratuitement ?",
      "description": "Il existe plusieurs façons d'obtenir des bijoux Guerre des Clans gratuitement. Cet article vous permet de découvrir toutes les méthodes efficaces. Si vous êtes parmi les chanceux aujourd'hui, vous pouvez ajouter une nouvelle méthode pour obtenir un code pour des bijoux Clash of Clans afin de développer votre village et votre armée rapidement et facilement, ou pour posséder les skins que vous avez toujours rêvé d'obtenir de manière légale et non piratée. De nombreux joueurs ont déjà gagné, et il reste encore des chances pour d'autres joueurs de gagner également.\n Plus il y a de participants au concours, plus vous avez de chances de gagner. N'oubliez donc pas de partager le concours avec vos amis pour augmenter vos chances aussi.",
      "step": {
        "one": {
          "title": "Entrez vos informations",
          "description": "Remplissez le formulaire ci-dessus pour participer au tirage hebdomadaire."
        },
        "two": {
          "title": "Tirage hebdomadaire",
          "description": "Chaque week-end, dix personnes chanceuses gagnent des bijoux."
        },
        "three": {
          "title": "Réception des cadeaux",
          "description": "Les cadeaux sont envoyés chaque week-end par e-mail."
        }
      }
    },
    "about": {
      "title": "Comment participer au concours ?",
      "description": "L'inscription ne vous prendra que quelques minutes, et vous pourrez ensuite obtenir des milliers de bijoux gratuitement 💎 dans le jeu Clash of Clans🔥 de manière garantie. Tout ce que vous avez à faire est de saisir vos informations personnelles et de terminer quelques tâches pour recevoir une notification dans votre boîte e-mail."
    },
    "steps": {
      "one": {
        "title": "Chaque joueur a droit à une seule participation",
        "description": "Participer plusieurs fois avec le même appareil peut vous disqualifier et vous empêcher de gagner un prix."
      },
      "two": {
        "title": "Les informations personnelles doivent être correctes",
        "description": "Ne pas fournir d'informations correctes peut entraîner la disqualification ou l'absence de réception des notifications dans votre e-mail."
      },
      "three": {
        "title": "Partagez le concours avec les membres de votre tribu",
        "description": "Pour augmenter vos chances, il est recommandé de partager le concours avec vos amis dans le jeu."
      }
    }
  },
  "footer": {
    "copyrights": {
      "one": "Copyright",
      "two": "Tous droits réservés"
    },
    "home": "Accueil",
    "terms": "Conditions d'utilisation",
    "policy": "Politique de confidentialité"
  },
  "other": {
    "title": {
      "agreement": "Confirmation de l'acceptation des conditions du tirage hebdomadaire"
    },
    "cta": {
      "selectgift": "Veuillez choisir"
    },
    "nav": "Comment utiliser ?"
  },
  "errors": {
    "gems": "• Veuillez choisir d'abord",
    "devices": "• Veuillez entrer le type d'appareil",
    "input": {
      "name": "• Veuillez entrer votre nom",
      "shortname": "• Veuillez entrer un nom valide",
      "terms": "• Veuillez accepter les conditions",
      "device": "• Veuillez choisir votre appareil"
    },
    "email": {
      "required": "• Veuillez entrer votre e-mail",
      "invalid": "• E-mail invalide"
    },
    "verification": "Veuillez terminer les tâches pour continuer"
  },
  "opengraph": {
    "title": "Bijoux Gratuits",
    "alt": "Bijoux Clash"
  },
  "keywords": {
    "one": "Bijoux Clash",
    "two": "Bijoux gratuits",
    "three": "Bijoux Guerre des Clans",
    "four": "Bijoux Clash of Clans",
    "five": "Bijoux Clash",
    "six": "Remplissage des réserves Clash",
    "seven": "GAGNER ENORMEMENT DE GEMMES",
    "eight": "GAGNER des diamonds"
  }
}