PATCH  http://localhost:3000/api/lang/656f462e4cb0e05cde00392d
Content-Type: application/json


 {
    "id": "656f462e4cb0e05cde00392d",
    "lang": "ru",
    "title": "Раздача самоцветов Clash Of Clans",
    "description": "Теперь вы можете выиграть неограниченное количество самоцветов Clash of Clans, чтобы покупать ресурсы и заполнить свои хранилища эликсира и золота до максимума. Всё, что вам нужно сделать, это заполнить опрос, чтобы получить код на самоцветы Clash of Clans и купить все скины, которые вам нравятся, в магазине. Заполните основные хранилища вашего села, улучшите своё село и армию, чтобы стать самым сильным в своём клане и самым сильным в клановых войнах.",
    "buttons": {
      "next": " Следующий",
      "back": " Назад",
      "submit": " Представить"
    },
    "labels": {
      "name": " Имя",
      "username": " Имя пользователя",
      "device": " Устройство",
      "email": " Адрес электронной почты",
      "wait": " Пожалуйста, Подождите",
      "emailNotice": " Примечание: Убедитесь что вы указали действительный адрес электронной почты"
    },
    "h1": {
      "one": "Раздача самоцветов",
      "two": "Second Empty"
    },
    "radio": {
      "device": {
        "android": " Андроид",
        "ios": "iOS",
        "other": " Другое устройство"
      },
"card": {
  "first": {
    "title": "Куча самоцветов",
    "amount": "1200",
    "image": "path",
    "alt": "Куча самоцветов"
  },
  "second": {
    "title": "Мешок самоцветов",
    "amount": "2500",
    "image": "path",
    "alt": "Мешок самоцветов"
  },
  "third": {
    "title": "Коробка самоцветов",
    "amount": "6500",
    "image": "path",
    "alt": "Коробка самоцветов"
  }
}
},
"section": {
  "howTo": {
    "title": "Как получить самоцветы Clash of Clans?",
    "description": "Если вы ищете способы получить некоторые самоцветы Clash of Clans, существует несколько способов сделать это бесплатно, используя методы, описанные в этой статье. \nНо если сегодня ваш удачный день, вы получите дополнительный шанс стать одним из победителей зелёных алмазов, которые ищут все. Многие игроки уже испытали удачу, и в будущем ещё будет много шансов для других. \nЧем больше игроков участвует в нашем опросе, тем больше возможностей будет заработать неограниченное количество самоцветов, и, поделившись раздачей с другом, вы сможете увеличить свои шансы на победу.",
    "step": {
      "one": {
        "title": "Подайте заявку на раздачу",
        "description": "Заполните форму выше, чтобы участвовать в еженедельной раздаче"
      },
      "two": {
        "title": "Выбор победителей",
        "description": "Счастливые победители выбираются каждые выходные"
      },
      "three": {
        "title": "Получите свой подарок",
        "description": "Код на получение подарка будет отправлен по электронной почте победителям"
      }
    }
  },
  "about": {
    "title": "Как подать заявку на раздачу?",
    "description": "Вам не потребуется более нескольких минут, чтобы получить шанс заработать самоцветы Coc, чтобы быстрее улучшить ваше село и армию и стать самым сильным членом вашего клана и получить свои любимые скины Clash of Clans. Всё, что вам нужно сделать, это заполнить вашу информацию, выполнить несколько простых задач, а затем дождаться уведомления с результатом на вашу электронную почту."
  },
  "steps": {
    "one": {
      "title": "Шаг первый: Заполните свою информацию",
      "description": "Укажите ваше имя и личный электронный адрес"
    },
    "two": {
      "title": "Шаг второй: Дождитесь выбора",
      "description": "Мы выбираем 10 победителей каждую неделю, возможно, вы будете одним из них"
    },
    "three": {
      "title": "Шаг третий: Получите свой код на получение подарка",
      "description": "Победители получат электронное письмо с кодом для получения своего подарка"
    }
  }
},
"footer": {
  "copyrights": {
    "one": "Авторское право",
    "two": "Все права защищены"
  },
  "home": "Главная",
  "terms": "Условия обслуживания",
  "policy": "Политика конфиденциальности"
},
    "other": {
      "title": {
        "agreement": " Я согласен с положениями и условиями "
      },
      "cta": {
        "selectgift": " Выбери свой подарок"
      },
      "nav": "Как использовать ?"
    },
    "errors": {
      "gems": "Пожалуйста, выберите один вариант ",
      "devices": "",
      "input": {
        "name": "• Требуется имя",
        "shortname": "• Слишком короткое имя",
        "terms": "• Принимайте условия",
        "device": "• Выберите своё устройство"
      },
      "email": {
        "required": "• Требуется электронная почта",
        "invalid": "• Введите действительный адрес электронной почты"
      },
      "verification": " Пожалуйста, завершите выполнение заданий чтобы продолжить "
    },
    "opengraph": {
      "title": "бесплатные самоцветы",
      "alt": "алмазы coc"
    },
"keywords": {
  "one": "Самоцветы Clash of Clans",
  "two": "Самоцветы Coc",
  "three": "Раздача Clash of Clans",
  "four": "Как получить самоцветы Clash of Clans",
  "five": "Бесплатные самоцветы Clash of Clans",
  "six": "Полное хранилище эликсира"
}
}





	
